netty.port: 8000
business.thread.count: 100
proxy.registry.address: zookeeper://127.0.0.1:2181
proxy.registry.group: dubbo
proxy.metadata-report.address: zookeeper://127.0.0.1:2181



#mapping:
#  services:
#   -
#    name: edf-system-service
#    interfaze: com.ttk.edf.system.itf.ISysRunningModeConfigService
#    group:
#    version:
